### ISSUE TITLE
Incomplete display of shading words in scan search box

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/blockscan#28]
![image](https://user-images.githubusercontent.com/77844990/177928926-7ec9b41e-a399-42e4-9648-30cfd3f80482.png)

**Comment by zmcNotafraid** [comment]
<img width="555" alt="image" src="https://github.com/Magickbase/blockscan/assets/12708910/d86ba911-76e9-4ff7-842e-5661b4a283ce">
<img width="394" alt="image" src="https://github.com/Magickbase/blockscan/assets/12708910/6b0032a3-342d-44ca-9fc8-ca85865d5a07">

I think this issue is not a bug.In phone view, it didn't display incompletely because of screen width.But in pc view, it looks good.
